env:
    browser: true
    es6: true
extends:
    - google
parser: typescript-eslint-parser
parserOptions:
    ecmaVersion: 2015
    sourceType: module
rules:
    linebreak-style:
        - error
        - unix
    indent:
        - error
        - 4

    max-len: off
    spaced-comment: off

    no-unused-vars: off
    require-jsdoc: off
    camelcase: off
